test_id: EX-E001-00000001
test_name: test-pileline
test_description: デモパイプライン：環境構築するけど、スクラップはしない。
namespace_name: demo-itst
parameters:
  environment:
    database: true
    kafka: true
    create_table: true
    insert_table: true
    create_table_image: create_table
    insert_table_image: insert_table
  test_scenario:
    delete_job: true
  closing:
    environment_remove: false
pipelines:
  - seq: 1
    type: init
    name: init-job
    description: 開始
  - seq: 2
    type: environment
    name: environment-workflow
    description: 環境構築
  - seq: 3
    type: test_scenario
    name: D2025-03-01
    description: 環境テスト
  - seq: 4
    type: test_scenario
    name: D2025-03-12
    description: アプリケーションのシナリオテスト
  - seq: 5
    type: closing
    name: closing-job
    description: 終了