test_id: EX-E001-00000002
test_name: report-pileline
test_description: report環境構築とテスト
namespace_name: demo-itst
parameters:
  environment:
    database: true
    kafka: true
    create_table: true
    insert_table: true
    create_table_image: create_table
    insert_table_image: insert_table
  test_scenario:
    - name: D2025-03-12
    - name: D2025-03-15
    - name: D2025-03-20
  closing:
    environment_remove: true
pipelines:
  - seq: 1
    type: init
    name: init-job
  - seq: 2
    type: environment
    name: environment-workflow
  - seq: 3
    type: test_scenario
    name: D2025-03-12
  - seq: 4
    type: test_scenario
    name: D2025-03-15
  - seq: 5
    type: test_scenario
    name: D2025-03-20
  - seq: 6
    type: closing
    name: closing-job
