test_id: EX-E001-00000003
test_name: demo-kafka-pileline
test_description: デモKafkaパイプライン
namespace_name: demo-kafka
parameters:
  environment:
    database: true
    kafka: true
    create_table: true
    insert_table: true
    create_table_image: create_table_demoapl
    insert_table_image: insert_table_demoapl
  test_scenario:
    delete_job: false
  closing:
    environment_remove: false
pipelines:
  - seq: 1
    type: init
    name: init-job
    description: 開始
  - seq: 2
    type: environment
    name: environment-workflow
    description: 環境構築
  - seq: 3
    type: test_scenario
    name: D2025-05-01
    description: 環境テスト
  - seq: 4
    type: closing
    name: closing-job
    description: 終了