apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo-itst
  name: report-viewer
  labels:
    app: report-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-viewer
  template:
    metadata:
      labels:
        app: report-viewer
    spec:
      containers:
        - name: report-viewer
          image: quay.io/rhn_consulting_kemori/report-viewer
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8088
              protocol: TCP
          env:
            - name: DB_HOST
              value: postgresql.demo-itst.svc.cluster.local
            - name: DB_NAME
              value: test
            - name: DB_PASS
              value: test
            - name: DB_PORT
              value: '5432'
            - name: DB_USER
              value: test  
      imagePullSecrets:
        - name: quayio
---
apiVersion: v1
kind: Service
metadata:
  name: report-viewer
  namespace: demo-itst
  labels:
    app: report-viewer
spec:
  type: ClusterIP
  ports:
    - name: 8088-tcp
      protocol: TCP
      port: 8088
      targetPort: 8088
  sessionAffinity: None
  selector:
    app: report-viewer
status:
  loadBalancer: {}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: report-viewer
  namespace: demo-itst
  labels:
    app: report-viewer
spec:
  host: report-viewer-demo-itst.apps.rosa.rosa-6hxjb.nnh2.p3.openshiftapps.com
  to:
    kind: Service
    name: report-viewer
    weight: 100
  port:
    targetPort: 8088-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
